apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 8Gi

