apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 10Gi

